### ISSUE TITLE
Setup Fails Rainbird ARC8

### ISSUE THREAD

**Issue by kzaoaai** [konikvranik/hacs_rainbird#12]
Hello,

I have this model which works with the HA native integration. I liked the idea of UI entry, so installed this repo.
However, I'm not able to set it up. Logs show the following error:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rainbird/__init__.py", line 92, in async_setup_entry
    await hass.async_add_executor_job(update_model_and_version)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rainbird/__init__.py", line 90, in update_model_and_version
    hass_data_raibird_[config_entry.entry_id].model_and_version = cli.get_model_and_version()
  File "/usr/local/lib/python3.10/site-packages/pyrainbird/__init__.py", line 40, in get_model_and_version
    return self._process_command(
  File "/usr/local/lib/python3.10/site-packages/pyrainbird/__init__.py", line 204, in _process_command
    funct(response)
  File "/usr/local/lib/python3.10/site-packages/pyrainbird/__init__.py", line 41, in <lambda>
    lambda response: ModelAndVersion(
  File "/usr/local/lib/python3.10/site-packages/pyrainbird/data.py", line 70, in __init__
    self.model_code = RAINBIRD_MODELS[self.model][0]
KeyError: 2067`

**Comment by konikvranik** [comment]
This is related to the https://github.com/jbarrancos/pyrainbird. So, please, create the issue there, or in my fork https://github.com/konikvranik/pyrainbird.
