### ISSUE TITLE
Dependency error?

### ISSUE THREAD

**Issue by luixal** [konikvranik/hacs_rainbird#5]
Hi,

I've just installed the integration adding the repo in my HACS custom repos. Installation went flawleslly. Then, I go to config and search for rainbird integration, which shows up:

![image](https://user-images.githubusercontent.com/615268/154337727-d6dfe72f-c1e2-4e90-b2d2-ef8a734407a4.png)

Once I click, it doesn't ask for any data (ip, password...) and just shows this error:

![image](https://user-images.githubusercontent.com/615268/154337805-01ec3deb-88db-4982-9a26-225f8dc54d8d.png)

Having a look at the logs, I show that it couldn't install package `pyrainbird=0.5.0`. I've seen that the last version in jbarrancos' repo is 0.4.3, pypi shows a 0.5.0 but when I installed it with pip for some custom testing (on my shell, not HA's) I also got 0.4.3.

This is the result of a `pip show pyrainbird` (on my shell, not the HA container):

```
Name: pyrainbird
Version: 0.4.3
Summary: Rain Bird Controller
Home-page: https://github.com/jbarrancos/pyrainbird/
Author: J.J.Barrancos
Author-email: jordy@fusion-ict.nl
License: MIT
Location: /home/nemesis/.local/lib/python3.10/site-packages
Requires: datetime, pycryptodome, requests, setuptools
Required-by: 
``` 
if I try to force version with `pip install -Iv pyrainbird==0.5.0` I get a bunch of errors:

```
Found link https://files.pythonhosted.org/packages/4e/1e/d15c493034097e2b976738ec061ad0a431c0121e02291837636be5b7ed75/pyrainbird-0.5.0.tar.gz#sha256=e85b921af138210982b53e69f4166a3af25461bec8982f4a60836f13e7c78ebe (from https://pypi.org/simple/pyrainbird/), version: 0.5.0
Given no hashes to check 1 links for project 'pyrainbird': discarding no candidates
Collecting pyrainbird==0.5.0
  Created temporary directory: /tmp/pip-unpack-tfve2mfj
  Looking up "https://files.pythonhosted.org/packages/4e/1e/d15c493034097e2b976738ec061ad0a431c0121e02291837636be5b7ed75/pyrainbird-0.5.0.tar.gz" in the cache
  Current age based on date: 105804
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 105804
  Using cached pyrainbird-0.5.0.tar.gz (6.6 kB)
  Added pyrainbird==0.5.0 from https://files.pythonhosted.org/packages/4e/1e/d15c493034097e2b976738ec061ad0a431c0121e02291837636be5b7ed75/pyrainbird-0.5.0.tar.gz#sha256=e85b921af138210982b53e69f4166a3af25461bec8982f4a60836f13e7c78ebe to build tracker '/tmp/pip-req-tracker-yb28ajck'
    Running setup.py (path:/tmp/pip-install-169n9o_7/pyrainbird_ebaf8ab658c141c1b2db117dc8d0fcda/setup.py) egg_info for package pyrainbird
    Created temporary directory: /tmp/pip-pip-egg-info-hswro3t1
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-169n9o_7/pyrainbird_ebaf8ab658c141c1b2db117dc8d0fcda/setup.py", line 7, in <module>
        with open("requirements.txt") as fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: Discarding https://files.pythonhosted.org/packages/4e/1e/d15c493034097e2b976738ec061ad0a431c0121e02291837636be5b7ed75/pyrainbird-0.5.0.tar.gz#sha256=e85b921af138210982b53e69f4166a3af25461bec8982f4a60836f13e7c78ebe (from https://pypi.org/simple/pyrainbird/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyrainbird==0.5.0
ERROR: No matching distribution found for pyrainbird==0.5.0
```

Any idea about this error? I think something wrong with the v.0.5.0 distribution of the pyrainbird package.

**Comment by jeremy-mattern** [comment]
I am getting this error too:

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble


Any help would be appreciated.

**Comment by konikvranik** [comment]
There is problem with the pyrinbirdlibrary: https://github.com/jbarrancos/pyrainbird/issues/38

**Comment by konikvranik** [comment]
I forked the pyrainbird library to alternative one. So current version of hacs_raibird works ok with pyrainbird-alternative:5.4.0
